version: '2'

services:
  app2:
    image: 'account-service:latest'
    build:
      context: .
    container_name: app2
    depends_on:
      - db
    ports:
      - "8082:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    networks:
      - dockernet            
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - dockernet  
networks:
    dockernet:            